Remove unallowed aria-required from <fieldset>
ctoec/component-library pull request #61
Opened 2020-09-08 21:49 UTC by jlhogan

2020-09-08 22:17 UTC, mmazanec22 commented on src/components/RadioButtonGroup/RadioButtonGroup.tsx
> +      role="radiogroup"
We don't need to add ARIA markup [when we're using native HTML elements](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA)-- it's for when we're doing shady things like using divs as buttons.

2020-09-08 22:17 UTC, mmazanec22 commented on src/components/FieldSet/FieldSet.tsx
> +  role?: 'presentation' | 'radiogroup';
What's the use case for the presentation role?

2020-09-08 22:24 UTC, mmazanec22 commented
@jlhogan what does this address?  From looking at it my hunch is that the issue was us using aria-required without using required-- from a little bit of digging it looks like they used to need to be used together, but that now NVDA and JAWS both will read the required attribute.  So I think maybe the fix we're looking for here is to ditch aria-required altogether and make it just required or not required.

Possibly there was some reason we used aria-required and not required in the first place-- some native form element behavior that we didn't want maybe?

2020-09-09 14:47 UTC, jlhogan commented
https://dequeuniversity.com/rules/axe/4.0/aria-allowed-attr?application=axeAPI -- the axe tests were failing, because apparently `aria-required` is not a valid label for a fieldset, unless that fieldset has `role` = `radiogroup`. Can definitely ditch aria-required (and role) for fieldset, and try just using required. i have no clue about the original impl of this thing

2020-09-09 20:50 UTC, mmazanec22 requested changes
Let's add role="radiogroup" to the radiogroup fieldset only to shush the axe error (even though that still seems wrong to me, it won't hurt), and maybe do that by just making the fieldset accept any valid html attribute for a fieldset in its props?  We definitely should not use role="presentation", since that would defeat the whole purpose of using a fieldset.  (A use case for the presentation role would be using tables for layout or something like that, where you're doing something unorthodox with an element and need to remove its semantic meaning.)

2020-09-11 15:23 UTC, jlhogan commented
I don't think that only adding radiogroup role to some of the fieldsets will solve the problem -- the issue is that axe doesn't like `aria-required` on the fieldset at all. So i think the simplest thing is just to remove aria-required from the fieldset ?

2020-09-11 16:20 UTC, mmazanec22 commented on src/components/FieldSet/FieldSet.tsx
> +          {optional ? <span className="usa-hint">&nbsp;(optional)</span> : <span className="usa-sr-only">(required)</span>}
Let's not add this to the legend-- it's weird to indicate this only to sr users, and it would be better to use a native HTML solution than rolling our own.  How about we just delete and make a ticket in the backlog, which should be addressed when we have any fields that are required and block save?

2020-09-11 16:26 UTC, mmazanec22 approved these changes

2020-09-11 20:48 UTC, merged